from bugzilla.dmbugzilla import DmBugzilla

###############################################################################


def test_build_createbug():
    bz = DmBugzilla(url=None)

    # Create empty
    result = bz.build_createbug()
    assert result == {}

    # Create with custom fields
    result = bz.build_createbug(
        cf_affected_modules='value of cf_affected_modules',
        cf_dmos_olt_version='value of cf_dmos_olt_version',
        cf_chamado_datacom='value of cf_chamado_datacom',
        cf_is_integrated_on_dmos='value of cf_is_integrated_on_dmos',
        cf_customer='value of cf_customer',
        cf_frequency='value of cf_frequency',
        cf_rally_team='value of cf_rally_team',
        cf_rally_team_drop='value of cf_rally_team_drop',
        cf_rally_synch='value of cf_rally_synch',
        cf_rally_id='value of cf_rally_id',
        cf_rally_url='value of cf_rally_url',
        cf_rally_rank='value of cf_rally_rank',
        cf_rally_iteration='value of cf_rally_iteration',
        cf_bug_impact='value of cf_bug_impact',
        cf_parent='value of cf_parent',
        cf_child='value of cf_child',
        cf_blocked='value of cf_blocked',
        cf_blocking_reason='value of cf_blocking_reason',
        cf_blocking_details='value of cf_blocking_details',
        cf_old_bug='value of cf_old_bug',
        cf_since='value of cf_since',
        cf_why_now='value of cf_why_now',
        cf_target='value of cf_target',
        cf_testcase='value of cf_testcase',
        cf_review_id='value of cf_review_id',
        cf_review_url='value of cf_review_url',
        cf_review_state='value of cf_review_state',
        cf_target_dmos_version='value of cf_target_dmos_version',
        cf_jenkins_job='value of cf_jenkins_job',
        cf_jenkins_phase='value of cf_jenkins_phase',
        cf_jenkins_build='value of cf_jenkins_build',
        cf_jenkins_cause='value of cf_jenkins_cause',
        cf_rn_presence='value of cf_rn_presence',
        cf_rn_category='value of cf_rn_category',
        cf_rn_retriction_version='value of cf_rn_retriction_version',
        cf_rn_details_text='value of cf_rn_details_text',
        cf_rn_ready='value of cf_rn_ready',
        cf_rn_done='value of cf_rn_done',
        cf_yodiz_url='value of cf_yodiz_url',
        cf_rank='value of cf_rank',
        cf_security_bug='value of cf_security_bug')
    assert result == {
        'cf_affected_modules': 'value of cf_affected_modules',
        'cf_dmos_olt_version': 'value of cf_dmos_olt_version',
        'cf_chamado_datacom': 'value of cf_chamado_datacom',
        'cf_is_integrated_on_dmos': 'value of cf_is_integrated_on_dmos',
        'cf_customer': 'value of cf_customer',
        'cf_frequency': 'value of cf_frequency',
        'cf_rally_team': 'value of cf_rally_team',
        'cf_rally_team_drop': 'value of cf_rally_team_drop',
        'cf_rally_synch': 'value of cf_rally_synch',
        'cf_rally_id': 'value of cf_rally_id',
        'cf_rally_url': 'value of cf_rally_url',
        'cf_rally_rank': 'value of cf_rally_rank',
        'cf_rally_iteration': 'value of cf_rally_iteration',
        'cf_bug_impact': 'value of cf_bug_impact',
        'cf_parent': 'value of cf_parent',
        'cf_child': 'value of cf_child',
        'cf_blocked': 'value of cf_blocked',
        'cf_blocking_reason': 'value of cf_blocking_reason',
        'cf_blocking_details': 'value of cf_blocking_details',
        'cf_old_bug': 'value of cf_old_bug',
        'cf_since': 'value of cf_since',
        'cf_why_now': 'value of cf_why_now',
        'cf_target': 'value of cf_target',
        'cf_testcase': 'value of cf_testcase',
        'cf_review_id': 'value of cf_review_id',
        'cf_review_url': 'value of cf_review_url',
        'cf_review_state': 'value of cf_review_state',
        'cf_target_dmos_version': 'value of cf_target_dmos_version',
        'cf_jenkins_job': 'value of cf_jenkins_job',
        'cf_jenkins_phase': 'value of cf_jenkins_phase',
        'cf_jenkins_build': 'value of cf_jenkins_build',
        'cf_jenkins_cause': 'value of cf_jenkins_cause',
        'cf_rn_presence': 'value of cf_rn_presence',
        'cf_rn_category': 'value of cf_rn_category',
        'cf_rn_retriction_version': 'value of cf_rn_retriction_version',
        'cf_rn_details_text': 'value of cf_rn_details_text',
        'cf_rn_ready': 'value of cf_rn_ready',
        'cf_rn_done': 'value of cf_rn_done',
        'cf_yodiz_url': 'value of cf_yodiz_url',
        'cf_rank': 'value of cf_rank',
        'cf_security_bug': 'value of cf_security_bug',
    }

###############################################################################


def test_build_update():
    bz = DmBugzilla(url=None)

    # Create empty
    result = bz.build_update()
    assert result == {}

    # Create with custom fields
    result = bz.build_update(
        cf_affected_modules='value of cf_affected_modules',
        cf_dmos_olt_version='value of cf_dmos_olt_version',
        cf_chamado_datacom='value of cf_chamado_datacom',
        cf_is_integrated_on_dmos='value of cf_is_integrated_on_dmos',
        cf_customer='value of cf_customer',
        cf_frequency='value of cf_frequency',
        cf_rally_team='value of cf_rally_team',
        cf_rally_team_drop='value of cf_rally_team_drop',
        cf_rally_synch='value of cf_rally_synch',
        cf_rally_id='value of cf_rally_id',
        cf_rally_url='value of cf_rally_url',
        cf_rally_rank='value of cf_rally_rank',
        cf_rally_iteration='value of cf_rally_iteration',
        cf_bug_impact='value of cf_bug_impact',
        cf_parent='value of cf_parent',
        cf_child='value of cf_child',
        cf_blocked='value of cf_blocked',
        cf_blocking_reason='value of cf_blocking_reason',
        cf_blocking_details='value of cf_blocking_details',
        cf_old_bug='value of cf_old_bug',
        cf_since='value of cf_since',
        cf_why_now='value of cf_why_now',
        cf_target='value of cf_target',
        cf_testcase='value of cf_testcase',
        cf_review_id='value of cf_review_id',
        cf_review_url='value of cf_review_url',
        cf_review_state='value of cf_review_state',
        cf_target_dmos_version='value of cf_target_dmos_version',
        cf_jenkins_job='value of cf_jenkins_job',
        cf_jenkins_phase='value of cf_jenkins_phase',
        cf_jenkins_build='value of cf_jenkins_build',
        cf_jenkins_cause='value of cf_jenkins_cause',
        cf_rn_presence='value of cf_rn_presence',
        cf_rn_category='value of cf_rn_category',
        cf_rn_retriction_version='value of cf_rn_retriction_version',
        cf_rn_details_text='value of cf_rn_details_text',
        cf_rn_ready='value of cf_rn_ready',
        cf_rn_done='value of cf_rn_done',
        cf_yodiz_url='value of cf_yodiz_url',
        cf_rank='value of cf_rank',
        cf_security_bug='value of cf_security_bug')
    assert result == {
        'cf_affected_modules': 'value of cf_affected_modules',
        'cf_dmos_olt_version': 'value of cf_dmos_olt_version',
        'cf_chamado_datacom': 'value of cf_chamado_datacom',
        'cf_is_integrated_on_dmos': 'value of cf_is_integrated_on_dmos',
        'cf_customer': 'value of cf_customer',
        'cf_frequency': 'value of cf_frequency',
        'cf_rally_team': 'value of cf_rally_team',
        'cf_rally_team_drop': 'value of cf_rally_team_drop',
        'cf_rally_synch': 'value of cf_rally_synch',
        'cf_rally_id': 'value of cf_rally_id',
        'cf_rally_url': 'value of cf_rally_url',
        'cf_rally_rank': 'value of cf_rally_rank',
        'cf_rally_iteration': 'value of cf_rally_iteration',
        'cf_bug_impact': 'value of cf_bug_impact',
        'cf_parent': 'value of cf_parent',
        'cf_child': 'value of cf_child',
        'cf_blocked': 'value of cf_blocked',
        'cf_blocking_reason': 'value of cf_blocking_reason',
        'cf_blocking_details': 'value of cf_blocking_details',
        'cf_old_bug': 'value of cf_old_bug',
        'cf_since': 'value of cf_since',
        'cf_why_now': 'value of cf_why_now',
        'cf_target': 'value of cf_target',
        'cf_testcase': 'value of cf_testcase',
        'cf_review_id': 'value of cf_review_id',
        'cf_review_url': 'value of cf_review_url',
        'cf_review_state': 'value of cf_review_state',
        'cf_target_dmos_version': 'value of cf_target_dmos_version',
        'cf_jenkins_job': 'value of cf_jenkins_job',
        'cf_jenkins_phase': 'value of cf_jenkins_phase',
        'cf_jenkins_build': 'value of cf_jenkins_build',
        'cf_jenkins_cause': 'value of cf_jenkins_cause',
        'cf_rn_presence': 'value of cf_rn_presence',
        'cf_rn_category': 'value of cf_rn_category',
        'cf_rn_retriction_version': 'value of cf_rn_retriction_version',
        'cf_rn_details_text': 'value of cf_rn_details_text',
        'cf_rn_ready': 'value of cf_rn_ready',
        'cf_rn_done': 'value of cf_rn_done',
        'cf_yodiz_url': 'value of cf_yodiz_url',
        'cf_rank': 'value of cf_rank',
        'cf_security_bug': 'value of cf_security_bug',
    }
